version: '3.8'

services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8000:8000"
  frontend:
    build: ./Application
    ports:
      - "8081:8081"
    # depends_on:
    #   - backend