# Generated by Django 5.1.1 on 2024-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
