# Generated by Django 5.1.1 on 2024-09-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_active_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_channel_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
