# Generated by Django 5.1.1 on 2024-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_active_channel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='active_channel_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
