# Generated by Django 5.1.1 on 2024-09-14 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_group', models.BooleanField(default=False)),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='channel_images/')),
                ('channel_profiles', models.ManyToManyField(related_name='channels', to='account.profile')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
    ]
