# Generated by Django 5.1.1 on 2024-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_image',
            new_name='image',
        ),
    ]
