# Generated by Django 5.1.1 on 2024-09-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_active_status_and_more'),
        ('channels_app', '0002_rename_channel_image_channel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_profiles',
            new_name='profiles',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED'), ('SEEN', 'SEEN'), ('FAILED', 'FAILED')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels_app.channel')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
            ],
        ),
    ]
