# Generated by Django 5.1.1 on 2024-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_profile_active_status_and_more'),
        ('channels_app', '0003_rename_channel_profiles_channel_profiles_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Conversation',
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='channel',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='profile',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_to',
            field=models.ManyToManyField(related_name='delivered_messages', to='account.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_messages', to='account.profile'),
        ),
    ]
